services:
  trading-api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: development
    image: trading-api:latest # Generic, reusable name
    container_name: trading-api
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://trading_user:changeme@postgres:5432/trading_db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=true
      - API_KEY_SECRET=dev-secret-key-change-in-production
      - RUN_MIGRATIONS=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  arq-worker:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: development
    image: arq-worker:latest # Generic, reusable name
    container_name: arq-worker
    environment:
      - DATABASE_URL=postgresql://trading_user:changeme@postgres:5432/trading_db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - trading-network
    restart: unless-stopped
    command: arq app.api.jobs.worker.WorkerSettings

networks:
  trading-network:
    driver: bridge
