# Minimal test environment for CI simulation
# Uses non-conflicting ports to avoid issues with local services

services:
  postgres:
    image: postgres:15-alpine
    container_name: trading_postgres_test
    ports:
      - '5433:5432' # Use 5433 externally to avoid conflicts
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
    tmpfs:
      - /var/lib/postgresql/data # Use tmpfs for faster tests
    networks:
      - trading_network_test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: trading_redis_test
    ports:
      - '6380:6379' # Use 6380 externally to avoid conflicts
    tmpfs:
      - /data # Use tmpfs for faster tests
    networks:
      - trading_network_test
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: redis-server --save "" --appendonly no # Disable persistence for tests

networks:
  trading_network_test:
    driver: bridge
