version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(funcName)s %(lineno)d %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 52428800 # 50MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 52428800 # 50MB
    backupCount: 5
    encoding: utf8

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/app.json
    maxBytes: 104857600 # 100MB
    backupCount: 3
    encoding: utf8

loggers:
  app:
    handlers: [console, file, json_file]
    level: INFO
    propagate: false

  app.api:
    handlers: [console, file, json_file]
    level: INFO
    propagate: false

  app.cli:
    handlers: [console, file]
    level: INFO
    propagate: false

  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: false

  uvicorn.access:
    handlers: [file]
    level: INFO
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
