[tool.poetry]
name = "trading"
version = "0.1.0"
description = ""
authors = ["Cole Morton"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = ">=1.16.5,<2.0.0"
vectorbt = "^0.26.2"
yfinance = "^0.2.41"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
