[tool.poetry]
name = "trading"
version = "0.1.0"
description = "Trading Strategy Platform with MA Cross, Portfolio Optimization, and GraphQL API"
authors = ["Cole Morton"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = ">=1.16.5,<2.0.0"
yfinance = "^0.2.41"
seaborn = "^0.13.2"
polars = "^1.5.0"
flask = "^3.0.3"
jupyter = "^1.1.1"
notebook = "^7.2.2"
ipywidgets = "^8.1.5"
pybit = "^5.8.0"
python-dotenv = "^1.0.1"
langchain = "^0.3.4"
langchain-community = "^0.3.3"
langchain-experimental = "^0.3.2"
langchain-ollama = "^0.2.0"
tabulate = "^0.9.0"
skfolio = "^0.6.0"
fastapi = "^0.110.0"
uvicorn = "^0.27.0"
pydantic = "^2.6.0"
strawberry-graphql = {version = "^0.236.0", extras = ["fastapi"]}
psutil = "^7.0.0"
langchain-anthropic = "^0.3.13"
asyncpg = "^0.29.0"
sqlalchemy = "^2.0.25"
alembic = "^1.13.0"
redis = "^5.0.1"
prisma = "^0.11.0"
pydantic-settings = "^2.9.1"
vectorbt = "^0.27.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^1.0.0"
pytest-cov = "^6.1.1"
black = "^24.0.0"
isort = "^5.13.0"
flake8 = "^7.0.0"
flake8-docstrings = "^1.7.0"
flake8-bugbear = "^24.0.0"
mypy = "^1.8.0"
pylint = "^3.0.0"
bandit = "^1.7.0"
vulture = "^2.11"
pre-commit = "^3.6.0"
autoflake = "^2.3.1"
autopep8 = "^2.3.2"
types-requests = "^2.32.0.20250602"
pytest-mock = "^3.14.1"
pytest-timeout = "^2.4.0"
pytest-xdist = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.10"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
# Make MyPy more practical for large codebases
ignore_errors = false
show_error_codes = true
# Allow untyped calls for now - we'll gradually improve
disallow_untyped_calls = false
# Focus on critical errors first - gradually enabling type checking
disable_error_code = ["misc", "union-attr", "attr-defined", "import-untyped", "unreachable", "index", "literal-required", "call-arg", "assignment", "arg-type", "name-defined", "method-assign"]
# Alternatively, use a more permissive approach for now
ignore_missing_imports = true

# Ignore third-party packages without type stubs
[[tool.mypy.overrides]]
module = [
    "vectorbt.*",
    "yfinance.*",
    "seaborn.*",
    "polars.*",
    "pybit.*",
    "langchain.*",
    "skfolio.*",
    "strawberry.*",
    "prisma.*",
    "plotly.*",
    "pandas_ta.*",
    "ta.*"
]
ignore_missing_imports = true

# Exclude vendor/external code
[[tool.mypy.overrides]]
module = "app.trading_bot.trendspider.*"
ignore_errors = true

[tool.pylint.messages_control]
disable = "C0103,C0114,C0115,C0116,R0903,R0913,W0613"

[tool.pylint.format]
max-line-length = 88

[tool.vulture]
min_confidence = 80
paths = ["app", "tests"]
exclude = ["*/migrations/*", "*/tests/*"]
