[tool.poetry]
name = "trading"
version = "0.1.0"
description = ""
authors = ["Cole Morton"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = ">=1.16.5,<2.0.0"
vectorbt = "^0.26.2"
yfinance = "^0.2.41"
seaborn = "^0.13.2"
polars = "^1.5.0"
flask = "^3.0.3"
jupyter = "^1.1.1"
notebook = "^7.2.2"
ipywidgets = "^8.1.5"
pybit = "^5.8.0"
python-dotenv = "^1.0.1"
langchain = "^0.3.4"
langchain-community = "^0.3.3"
langchain-experimental = "^0.3.2"
langchain-ollama = "^0.2.0"
tabulate = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
