# MA Cross Portfolio Analysis Configuration
# YAML equivalent of the CONFIG from app/strategies/ma_cross/1_get_portfolios.py
#
# This file contains the strategy-specific configuration for MA Cross portfolio analysis.
# It corresponds directly to the Python CONFIG dict in 1_get_portfolios.py

# Ticker list from the original CONFIG
ticker:
  - 'BKR'
  - 'DAL'
  - 'BK'
  - 'ISRG'
  - 'IFF'
  - 'VRTX'
  - 'EXR'
  - 'TECH'
  - 'MTD'
  - 'IONQ'
  - 'QBTS'
  - 'NTAP'
  - 'BIIB'
  - 'UAL'
  - 'MCHP'
  - 'VFC'
  - 'ALK'
  - 'LEG'

# Alternative ticker configurations (commented in original)
# Alternative high-performance tickers:
# ticker:
#   - "HWM"
#   - "NFLX"
#   - "NVDA"
#   - "TPR"
#   - "RTX"
#   - "AMD"
#   - "FFIV"
#   - "TEM"
#   - "BLDR"
#   - "SMCI"
#   - "QCOM"
#   - "SCHW"
#   - "DOV"
#   - "VRSN"
#   - "RJF"
#   - "GME"

# Strategy parameters
windows: 89 # Alternative values in original: 120, 55, 34
strategy_types:
  - 'SMA'
  - 'EMA'
  # - "SMA"  # SMA only option
direction: 'Long'

# Time configuration
use_hourly: false
use_years: false
years: 15

# Feature flags
use_synthetic: false
use_current: true
use_gbm: false
refresh: true

# Optional scanner configuration (commented in original)
# scanner_list: "DAILY.csv"
# use_scanner: true

# Optional synthetic ticker configuration
# ticker_2: "AVGO"

# Performance filtering criteria
minimums:
  win_rate: 0.5
  trades: 44
  # Alternative thresholds in original comments:
  # win_rate: 0.50
  # trades: 54
  # win_rate: 0.61
  expectancy_per_trade: 0.5
  profit_factor: 1.236
  sortino_ratio: 0.5
  # beats_bnh: 0      # Optional beat buy-and-hold requirement
  # beats_bnh: 0.13   # Alternative beat buy-and-hold requirement

# Result sorting
sort_by: 'Score'
sort_ascending: false
