name: Pre-commit Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python & Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Install pre-commit
        run: poetry run pre-commit install --install-hooks

      - name: Run pre-commit hooks on all files
        run: poetry run pre-commit run --all-files --show-diff-on-failure
        env:
          SKIP: '' # Don't skip any hooks

      - name: Generate failure summary
        if: failure()
        run: |
          echo "## ❌ Pre-commit Checks Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pre-commit hooks found issues that must be fixed." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Common Fixes" >> $GITHUB_STEP_SUMMARY
          echo "1. **Formatting Issues (Ruff)**: Run \`poetry run ruff format .\`" >> $GITHUB_STEP_SUMMARY
          echo "2. **Linting Issues (Ruff)**: Run \`poetry run ruff check --fix .\`" >> $GITHUB_STEP_SUMMARY
          echo "3. **Type Issues (MyPy)**: Add type annotations or fix type errors" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### How to Fix Locally" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Install pre-commit hooks" >> $GITHUB_STEP_SUMMARY
          echo "poetry run pre-commit install" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Run all pre-commit hooks" >> $GITHUB_STEP_SUMMARY
          echo "poetry run pre-commit run --all-files" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Or run verification script" >> $GITHUB_STEP_SUMMARY
          echo "./scripts/verify-commit.sh" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Comprehensive security scans run daily via security.yml workflow" >> $GITHUB_STEP_SUMMARY

      - name: Generate success summary
        if: success()
        run: |
          echo "## ✅ All Pre-Commit Checks Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All code quality checks have passed successfully." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Code formatting (Ruff)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Code linting (Ruff)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Type checking (MyPy)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Frontend linting (ESLint)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Frontend formatting (Prettier)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Comprehensive security scans run daily at 3 AM UTC via security.yml workflow" >> $GITHUB_STEP_SUMMARY
