name: Unit Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests (Fast Feedback)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python & Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Validate test markers
        run: |
          poetry run python tests/validate_markers.py --stats
          echo "📊 Marker validation complete"

      - name: Run unit tests
        run: |
          poetry run pytest -m unit \
            -n auto \
            --maxfail=10 \
            --tb=short \
            --color=yes \
            -v \
            --junitxml=test-results/unit-tests.xml
        timeout-minutes: 3

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: test-results/

      - name: Test Summary
        if: always()
        run: |
          if [ -f test-results/unit-tests.xml ]; then
            echo "✅ Unit tests completed"
            grep -oP 'tests="\K[0-9]+' test-results/unit-tests.xml || echo "0"
          fi
